### ISSUE TITLE
[BUG] More storage - Can't click "Craft" button in the church

### ISSUE THREAD

**Issue by Marianna-Milorzab** [p1xel8ted/GYK-Mods-QMod#15]
![image](https://user-images.githubusercontent.com/78551038/173248296-f16a451d-da0a-41b2-8f88-8b07e9db0bed.png)

**What mod/tool are you reporting a bug for?**
- Mod: More storage
- Version 2.4

**Issue**
- "Craft" button at the praying altar in the church is unclickable when "More storage" is enabled

**Expected behavior**
- "Craft" button should be clickable

**Desktop (please complete the following information):**
- Windows 10
- Windows language: English
- Game language: English
- Game platform: gog

**Additional context**
- After disabling More storage mod, the craft button started being clickable.
- Workaround: clicking right-hand mouse button outside of the "craft" button starts a prayer/crafting

**Comment by p1xel8ted** [comment]
#18

**Comment by p1xel8ted** [comment]
This was due to Queue Everything, fixed in 1.3
