### ISSUE TITLE
[BUG] Unable to sharpen tools or craft sermon with 1.2 version of Queue Everything mod

### ISSUE THREAD

**Issue by Althalus28** [p1xel8ted/GYK-Mods-QMod#18]
**Requirements**
![image](https://user-images.githubusercontent.com/44215027/175617621-f00e9dea-4833-4434-bb93-40f6240e3a53.png)

**Required Logs**
Please delete both logs and test the game again so it generates fresh logs with only relevant entries.
- C:\Users\<username>\AppData\LocalLow\Lazy Bear Games\Graveyard Keeper\Player.log
[Player.log](https://github.com/p1xel8ted/GYK-Mods-QMod/files/8978989/Player.log)

- ...\Graveyard Keeper\qmod_reloaded_log.txt
[qmod_reloaded_log.txt](https://github.com/p1xel8ted/GYK-Mods-QMod/files/8978993/qmod_reloaded_log.txt)

**What mod are you reporting a bug for?**
- Queue Everything
- 1.2
- Nexus

**Describe the bug**
- Unable to fix tools, as it is looking for both two of the tool and two of the whetstones.
- Unable to perform sermon as the Craft Button is greyed out.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Go to Grindstone
2. Click on Blank Square Square
3. Select a Tool and see what is required

1. Go to Pulpit in Church
2. Select Sermon.
3. See that the Craft Button is not able to be pushed.

**Expected behavior**
- A clear and concise description of what you expected to happen.
- Being able to repair the tools at the grindstone and being able to perform a sermon.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/44215027/175621507-149a2dab-866d-4a89-9803-84429d3682e5.png)

![image](https://user-images.githubusercontent.com/44215027/175619025-9dcd7471-71f1-4ddb-8a28-ac4099b00ce5.png)

**Desktop (please complete the following information):**
- Windows 10
- English
- English
- Steam

**Additional context**
- Only occurred with the most recent update.

**Comment by p1xel8ted** [comment]
[QueueEverything.v1.3.zip](https://github.com/p1xel8ted/GYK-Mods-QMod/files/8983852/QueueEverything.v1.3.zip)

Can you please try this one and report back.
