### ISSUE TITLE
[BUG] Broken sword shows as 1/2 + whetstone as 1/2 on the grindstone with queue everything v1.4

### ISSUE THREAD

**Issue by FloppyGlass** [p1xel8ted/GYK-Mods-QMod#19]
**Requirements**
- Please include a screenshot of QMod Manager Reloaded so that I can see what mods you have installed and their load order.
![qmod_mgr_1](https://user-images.githubusercontent.com/15704671/175849705-60c17c0f-54c0-49aa-b927-1fa8a0d7635e.PNG)
![qmod_mgr_2](https://user-images.githubusercontent.com/15704671/175849706-64087e3a-5095-4733-b0f5-5974204b6712.PNG)

**Required Logs**
Please delete both logs and test the game again so it generates fresh logs with only relevant entries.
- C:\Users\<username>\AppData\LocalLow\Lazy Bear Games\Graveyard Keeper\Player.log
- ...\Graveyard Keeper\qmod_reloaded_log.txt
[qmod_reloaded_log.txt](https://github.com/p1xel8ted/GYK-Mods-QMod/files/8988279/qmod_reloaded_log.txt)
[Player.log](https://github.com/p1xel8ted/GYK-Mods-QMod/files/8988280/Player.log)

**What mod are you reporting a bug for?**
- Mod: Queue Everything
- Version: 1.4
- Where did you download it from: https://www.nexusmods.com/graveyardkeeper/mods/57

**Describe the bug**
- Trying to fix the broken sword in the blacksmith quest shows as 1/2 + whetstone as 1/2 on the grindstone with queue everything v1.4

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Start new game
2. Complete scripted sequence till you meet bishop
3. Go to town and meet the inn keeper and get the letter to blacksmith
4. Meet blacksmith and give him letter and then get his quest
5. Blacksmith gives 1 whetstone + 1 broken sword to kill jellies
6. Try to fix broken sword on grindstone
7. Observe that the stated requirement is 1/2 broken sword + 1/2 whetstone and fix button won't work in this state

**Expected behavior**
- Requirement to fix broken sword on grindstone should be: 1/1 broken sword + 1/1 whetstone

**Screenshots/Video**
- If applicable, add screenshots to help explain your problem or provide a YouTube link.
I went past the start of the game already multiple times. Will need to restart and get a fresh screen. Will paste once I have one.

**Desktop (please complete the following information):**
- Windows version: 10 Home
- Windows language: SL English
- Game language: English
- Game platform: Steam

**Additional context**
- Add any other context about the problem here.

**Comment by p1xel8ted** [comment]
No need for the other stuff. Looking at my code again and I can see what's wrong. I forgot to include sword in the inclusions if stuff to ignore

**Comment by p1xel8ted** [comment]
**Queue Everything v1.5**
```
- Fixed swords not being able to be used in the grindstone. Thanks to those that reported it.

https://www.nexusmods.com/graveyardkeeper/mods/57?tab=files
```
