### ISSUE TITLE
[BUG] Cannot craft flyers

### ISSUE THREAD

**Issue by FloppyGlass** [p1xel8ted/GYK-Mods-QMod#20]
**Requirements**
- Please include a screenshot of QMod Manager Reloaded so that I can see what mods you have installed and their load order.
![qmod_mgr_1](https://user-images.githubusercontent.com/15704671/176110674-64a8f81a-c13c-448a-bd1e-084797c0e166.PNG)
![qmod_mgr_2](https://user-images.githubusercontent.com/15704671/176110693-35562a52-fa86-49d5-a2f2-811cd380ab49.PNG)

**Required Logs**
Please delete both logs and test the game again so it generates fresh logs with only relevant entries.
- C:\Users\<username>\AppData\LocalLow\Lazy Bear Games\Graveyard Keeper\Player.log
- ...\Graveyard Keeper\qmod_reloaded_log.txt
[qmod_reloaded_log.txt](https://github.com/p1xel8ted/GYK-Mods-QMod/files/8998299/qmod_reloaded_log.txt)
[Player.log](https://github.com/p1xel8ted/GYK-Mods-QMod/files/8998300/Player.log)

**What mod are you reporting a bug for?**
- Mod: Misc. Bits and Bobs
- Version: 1.3
- Where did you download it from: https://www.nexusmods.com/graveyardkeeper/mods/55

**Describe the bug**
- A clear and concise description of what the bug is.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Go to church desk
2. Click on church desk
3. Scroll down to flyers craft
4. Make sure you have required items to craft
5. Click on the flyer craft
6. Nothing happens, the dialog remains open

**Expected behavior**
- Dialog should close with the Work 'F' prompt to create the flyer

**Screenshots/Video**
- If applicable, add screenshots to help explain your problem or provide a YouTube link.

**Desktop (please complete the following information):**
- Windows version: 10
- Windows language: Eng
- Game language : Enf
- Game platform: Steam

**Additional context**
- Add any other context about the problem here.

Clicking on the craft does nothing. There is no max button either. I checked by disabling only this mod and it works again (though max button still does not show but I am able to craft the flyers one by one)

![game](https://user-images.githubusercontent.com/15704671/176111060-121a6522-d150-4680-9414-1b0b42ec1d1d.PNG)

**Comment by p1xel8ted** [comment]
Yeah MaxButton seems to pick and choose what frames it attaches to. Thanks for making the effort to report this, can you please try this one?
[MiscBitsAndBobs.v1.4.zip](https://github.com/p1xel8ted/GYK-Mods-QMod/files/8999013/MiscBitsAndBobs.v1.4.zip)
@FloppyGlass

**Comment by p1xel8ted** [comment]
Hey mate, is it the same desk to craft the flyer? Can you please re-post the Unity log.

**Comment by FloppyGlass** [comment]
Here you go
[qmod_reloaded_log.txt](https://github.com/p1xel8ted/GYK-Mods-QMod/files/9016744/qmod_reloaded_log.txt)
[Player.log](https://github.com/p1xel8ted/GYK-Mods-QMod/files/9016745/Player.log)

**Comment by FloppyGlass** [comment]
To give you some more details, this was on a desk 1, and I think I faced the issue crafting the notes/chapters as well (nothing happens when I click craft). I will try all of this on a desk 2 sometime today.

**Comment by p1xel8ted** [comment]
> To give you some more details, this was on a desk 1, and I think I faced the issue crafting the notes/chapters as well (nothing happens when I click craft). I will try all of this on a desk 2 sometime today.

Looks like it's every "paper" type item that uses the pen and ink as a craft. I'll have to do a blanket fix on them all

**Comment by p1xel8ted** [comment]
[MiscBitsAndBobs.v1.5.zip](https://github.com/p1xel8ted/GYK-Mods-QMod/files/9017404/MiscBitsAndBobs.v1.5.zip)

Try this. Basically, any craft that takes durability damage over time and uses the pen/ink as an ingredient should return false when the game checks for that combination

@FloppyGlass
