### ISSUE TITLE
[BUG] Can't remove gravestones or grave fences

### ISSUE THREAD

**Issue by SamHutton7** [p1xel8ted/GYK-Mods-QMod#21]
**Requirements**
- Please include a screenshot of QMod Manager Reloaded so that I can see what mods you have installed and their load order.

![image](https://user-images.githubusercontent.com/90610685/177300418-be97cb39-3a18-477d-8075-b9f7f5b7837f.png)

**Required Logs**
Please delete both logs and test the game again so it generates fresh logs with only relevant entries.
- C:\Users\<username>\AppData\LocalLow\Lazy Bear Games\Graveyard Keeper\Player.log
- ...\Graveyard Keeper\qmod_reloaded_log.txt
- 
[Player.log](https://github.com/p1xel8ted/GYK-Mods-QMod/files/9045287/Player.log)

[qmod_reloaded_log.txt](https://github.com/p1xel8ted/GYK-Mods-QMod/files/9045289/qmod_reloaded_log.txt)

**What mod are you reporting a bug for?**
- Mod Misc. Bits and Bobs
- Version 1.5
- Where did you download it from https://github.com/p1xel8ted/GYK-Mods-QMod/files/9017404/MiscBitsAndBobs.v1.5.zip

**Describe the bug**
- A clear and concise description of what the bug is.
When attempting to remove either gravestones or grave fences, the item is not removed from the grave however gets added to your inventory as if it had been. Some items do eventually get removed if you keep attempting it however some do not.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Go to graveyard
2. Click on any grave with a grave stone or grave fence
3. Click on grave stone section
4. Click remove
5. Hold F to craft
6. See item has not been removed but has been added to inventory and you can continue to remove it over and over

**Expected behavior**
- Gravestone/fence is removed and added to inventory. Will then allow you to add a new stone/fence to the grave

**Screenshots/Video**
- If applicable, add screenshots to help explain your problem or provide a YouTube link.
- Screenshot shows where i have attempted to remove a stone/fence
![image](https://user-images.githubusercontent.com/90610685/177302250-6f08cbe4-b9fc-4a91-baa6-a353e0f445c0.png)

**Desktop (please complete the following information):**
- Windows version 10
- Windows language Eng
- Game language Eng
- Game platform Steam

**Additional context**
- Add any other context about the problem here.

**Comment by p1xel8ted** [comment]
@https://www.nexusmods.com/graveyardkeeper/mods/55?tab=files

Download the ones from Nexus. The only mods you need to get from my GitHub are the Harmon1-2 conversions. Despite the version number, the one on Nexus is newer.

@SamHutton7

**Comment by SamHutton7** [comment]
Ah right, works perfectly now.

Thanks mate!
