### ISSUE TITLE
[BUG] Longer Days is missing the Config.ini

### ISSUE THREAD

**Issue by Werekitty39501** [p1xel8ted/GYK-Mods-QMod#22]
The Longer Days mod V4 currently on Nexus doesn't have the Config.ini to configure the longer days.

**Comment by p1xel8ted** [comment]
Start the game, and it will generate a default.

**Comment by Werekitty39501** [comment]
Is it only supposed to have the dll and the json? I've opened it a couple of times, and it hasn't produced a config.
![Longer Days Folder](https://user-images.githubusercontent.com/103905910/178129044-edd8252e-0767-433f-9dce-9763baf2182d.jpg)

**Comment by p1xel8ted** [comment]
How are you launching the game, and is the mod enabled in the UI? I just tested it on my machine it generates a config file as expected.
