### ISSUE TITLE
Issue: Can't Sell

### ISSUE THREAD

**Issue by LilLaTLuv** [p1xel8ted/GYK-Mods-QMod#23]
First, I couldn't build with this on but I figured out that MaxButton was conflicting with it, and disabled that. Now, I went to the tavern to sell my death certificate, and it won't let me. I click on it and it won't drop into the sell section. I just updated all of my mods with the latest updates, just so you're aware. However, I do have a few mods running:

- Exhaust-less
- Gerry's Junk Trunk
- Where's Ma Storage
- Longer Days
- Apple Trees Enhanced!
- No Time for Fishing!
- Save Now!
- I Build Where I Want
- Queue Everything!
- I NEEEEEED Sticks!
- The Seed Equalizer
- Thoughtful Reminders

When disabling Where's Ma Storage, I am able to sell as usual so I know something in this mod is the culprit. Reenabling just makes my inventory go away completely and nothing work at all. Also, if it helps, your Misc. Bits and Bobs also has the same results when added. Can't sell, and can't build. Any ideas? I really want to use this mod, especially with the I Build Where I Want mod enabled! Thank you for your time and efforts, let me know if you need any other information, and I hope you have a wonderful day.

**Comment by p1xel8ted** [comment]
I posted a few updates to these yesterday. Can you please update them and see if it resolves your issue?

**Comment by LilLaTLuv** [comment]
Oh sorry, I forgot to update you! Worked like a charm! Thank you so much for your hard work.
