### ISSUE TITLE
[BUG] Garys Junk Trunk interferes with I Build where i want

### ISSUE THREAD

**Issue by Quinthal** [p1xel8ted/GYK-Mods-QMod#24]
**Requirements**
- Please include a screenshot of QMod Manager Reloaded so that I can see what mods you have installed and their load order.
QMod Manager Reloaded-40-1-0-8255-15185-1659966460

used mods and loadorder the window is too short to show all mods in the qmod screenshot

add straight to table 2.2
AutoLootHeavies 3.2
Exhaust Less 7.3
Beam me up Gary 1.6
Economy reloaded 1.0
Gary Junk trunk 1.5... deactivated because of the problem
Longer days 4.1
I Build where i want 1.5
Apple Trees Enhanced 2.6.1
New Game at Button 2.1
Misc Bits & Bobs  1.9.1 ModifyPlayerMovementSpeed=false the player was uncontrollable fast while true
No Time for fishing 3.1
Queue everything 1.9.3
Regeneration Reloaded 1.0
I Need Sticks 1.4
The Seed Equalizer 1.1
Thoughtful Reminders 2.1
Where is the Storage 1.8.1

**Required Logs**
Please delete both logs and test the game again so it generates fresh logs with only relevant entries.
- C:\Users\<username>\AppData\LocalLow\Lazy Bear Games\Graveyard Keeper\Player.log
- ...\Graveyard Keeper\qmod_reloaded_log.txt
Logs deleted no effect

**What mod are you reporting a bug for?**
- Mod I Build where i want 1.5
- Gary Junk trunk 1.5 interferes with I Build where i want

- Where did you download it from
https://www.nexusmods.com/graveyardkeeper?tab=latest

**Describe the bug**
- A clear and concise description of what the bug is.
I Tested which Mod caused that the Build everywhere window is empty with e second use. I shutdown every mod and then activated one after another until the Problem appeared. It was Garys Junk Trunk
I disabled Garys Junk Trunk and the Mod works. 
I tried it sereal times to actived/deactivate and tryed if the loadorder changes anything. The result was everythime the same as above

**To Reproduce**

 use LB to open the window close it and the second time using it the window ist empty

**Screenshots/Video**
- If applicable, add screenshots to help explain your problem or provide a YouTube link.
https://s20.directupload.net/images/220813/q3utpcfj.jpg
<a href="https://www.directupload.net" target="_blank"><img src="https://s20.directupload.net/images/220813/q3utpcfj.jpg" title="Kostenlos Bilder und Fotos hochladen"></a>

**Desktop (please complete the following information):**
- Windows version 10
- Windows language german
- Game language german

**Comment by p1xel8ted** [comment]
The purpose of the logs was so I can look through them. Please attach the following:

- Your entire QMod directory in a ZIP/RAR file
- The save game that it occurs on (save folder can be opened from the QMR File menu)
- The log files as mentioned above

**Comment by Quinthal** [comment]
Did you received the files? i sent it per email

**Comment by p1xel8ted** [comment]
> Did you received the files? i sent it per email

Hey mate - Nah nothing - you can just attach them to this report.

**Comment by Quinthal** [comment]
[](url
[Player.log](https://github.com/p1xel8ted/GYK-Mods-QMod/files/9394623/Player.log)
[qmod_reloaded_log.txt](https://github.com/p1xel8ted/GYK-Mods-QMod/files/9394626/qmod_reloaded_log.txt)
[QMods.zip](https://github.com/p1xel8ted/GYK-Mods-QMod/files/9394629/QMods.zip)
[Savegame1.zip](https://github.com/p1xel8ted/GYK-Mods-QMod/files/9394630/Savegame1.zip)
)

**Comment by p1xel8ted** [comment]
Please ensure all the installed mods you have, have been updated, including QMod Manager Reloaded, and then try the attached ZIP file.

[GerrysJunkTrunk.v1.6-test.zip](https://github.com/p1xel8ted/GYK-Mods-QMod/files/9401989/GerrysJunkTrunk.v1.6-test.zip)

**Comment by p1xel8ted** [comment]
Also, MaxButton and its config should be in a folder called MaxButton, not loose in the QMod directory. The only DLL that should be in that folder, is Helper.dll

**Comment by Quinthal** [comment]
The fix is working

**Comment by p1xel8ted** [comment]
> The fix is working

excellent, ok to close the issue now?

**Comment by Quinthal** [comment]
yes

**Comment by Quinthal** [comment]
13.08.2022 14:28:23 : Add Straight To Table! added.
13.08.2022 14:28:23 : Apple Trees Enhanced! added.
13.08.2022 14:28:23 : AutoLootHeavies added.
13.08.2022 14:28:23 : Beam Me Up Gerry! added.
13.08.2022 14:28:23 : Economy Reloaded! added.
13.08.2022 14:28:23 : Exhaust-less added.
13.08.2022 14:28:23 : Gerry's Junk Trunk added.
13.08.2022 14:28:23 : I Build Where I Want! added.
13.08.2022 14:28:23 : I Neeeed Sticks! added.
13.08.2022 14:28:23 : Longer Days added.
13.08.2022 14:28:23 : MaxButton added.
13.08.2022 14:28:23 : MaxButton Controller Support added.
13.08.2022 14:28:23 : Misc. Bits & Bobs added.
13.08.2022 14:28:23 : New Game ... At Bottom added.
13.08.2022 14:28:23 : No Time For Fishing! added.
13.08.2022 14:28:23 : Queue Everything!* added.
13.08.2022 14:28:23 : Regeneration Reloaded! added.
13.08.2022 14:28:23 : The Seed Equalizer added.
13.08.2022 14:28:23 : Thoughtful Reminders added.
13.08.2022 14:28:23 : Where's Ma' Storage! added.
13.08.2022 14:28:23 : All mods with an entry point added. This doesn't mean they'll load correctly or function if they do load.
13.08.2022 14:28:23 : Updating mod.json files for all installed mods. Information is pulled from the mods directly.
13.08.2022 14:28:36 : Successfully invoked QMod Helper entry method.
13.08.2022 14:28:36 : Assembly-CSharp.dll has been patched, (otherwise you wouldn't see this message.
13.08.2022 14:28:36 : Patch method called. Attempting to load mods.
13.08.2022 14:28:36 : Load order: 1, successfully invoked Add Straight To Table! entry method.
13.08.2022 14:28:36 : Load order: 3, successfully invoked AutoLootHeavies entry method.
13.08.2022 14:28:36 : Load order: 4, successfully invoked Exhaust-less entry method.
13.08.2022 14:28:36 : Load order: 6, successfully invoked Beam Me Up Gerry! entry method.
13.08.2022 14:28:36 : Load order: 7, successfully invoked Economy Reloaded! entry method.
13.08.2022 14:28:36 : Load order: 10, successfully invoked Gerry's Junk Trunk entry method.
13.08.2022 14:28:37 : Load order: 11, successfully invoked MaxButton entry method.
13.08.2022 14:28:37 : Load order: 12, successfully invoked Longer Days entry method.
13.08.2022 14:28:37 : Load order: 13, successfully invoked Apple Trees Enhanced! entry method.
13.08.2022 14:28:37 : Load order: 13, successfully invoked I Build Where I Want! entry method.
13.08.2022 14:28:37 : Load order: 17, successfully invoked New Game ... At Bottom entry method.
13.08.2022 14:28:37 : Load order: 18, successfully invoked MaxButton Controller Support entry method.
13.08.2022 14:28:37 : Load order: 19, successfully invoked Misc. Bits & Bobs entry method.
13.08.2022 14:28:37 : Load order: 19, successfully invoked No Time For Fishing! entry method.
13.08.2022 14:28:37 : Load order: 21, successfully invoked Queue Everything!* entry method.
13.08.2022 14:28:37 : Load order: 24, successfully invoked Regeneration Reloaded! entry method.
13.08.2022 14:28:37 : Load order: 26, successfully invoked I Neeeed Sticks! entry method.
13.08.2022 14:28:37 : Load order: 27, successfully invoked The Seed Equalizer entry method.
13.08.2022 14:28:37 : Load order: 29, successfully invoked Thoughtful Reminders entry method.
13.08.2022 14:28:37 : Load order: 29, successfully invoked Where's Ma' Storage! entry method.
13.08.2022 14:30:35 : Successfully invoked QMod Helper entry method.
13.08.2022 14:30:35 : Assembly-CSharp.dll has been patched, (otherwise you wouldn't see this message.
13.08.2022 14:30:35 : Patch method called. Attempting to load mods.
13.08.2022 14:30:35 : Load order: 1, successfully invoked Add Straight To Table! entry method.
13.08.2022 14:30:36 : Load order: 3, successfully invoked AutoLootHeavies entry method.
13.08.2022 14:30:36 : Load order: 4, successfully invoked Exhaust-less entry method.
13.08.2022 14:30:36 : Load order: 6, successfully invoked Beam Me Up Gerry! entry method.
13.08.2022 14:30:36 : Load order: 7, successfully invoked Economy Reloaded! entry method.
13.08.2022 14:30:36 : Load order: 10, successfully invoked Gerry's Junk Trunk entry method.
13.08.2022 14:30:36 : Load order: 11, successfully invoked MaxButton entry method.
13.08.2022 14:30:36 : Load order: 12, successfully invoked Longer Days entry method.
13.08.2022 14:30:36 : Load order: 13, successfully invoked Apple Trees Enhanced! entry method.
13.08.2022 14:30:36 : Load order: 13, successfully invoked I Build Where I Want! entry method.
13.08.2022 14:30:36 : Load order: 17, successfully invoked New Game ... At Bottom entry method.
13.08.2022 14:30:36 : Load order: 18, successfully invoked MaxButton Controller Support entry method.
13.08.2022 14:30:36 : Load order: 19, successfully invoked Misc. Bits & Bobs entry method.
13.08.2022 14:30:36 : Load order: 19, successfully invoked No Time For Fishing! entry method.
13.08.2022 14:30:36 : Load order: 21, successfully invoked Queue Everything!* entry method.
13.08.2022 14:30:36 : Load order: 24, successfully invoked Regeneration Reloaded! entry method.
13.08.2022 14:30:36 : Load order: 26, successfully invoked I Neeeed Sticks! entry method.
13.08.2022 14:30:36 : Load order: 27, successfully invoked The Seed Equalizer entry method.
13.08.2022 14:30:36 : Load order: 29, successfully invoked Thoughtful Reminders entry method.
13.08.2022 14:30:37 : Load order: 29, successfully invoked Where's Ma' Storage! entry method.
13.08.2022 14:41:26 : Add Straight To Table! added.
13.08.2022 14:41:27 : Apple Trees Enhanced! added.
13.08.2022 14:41:27 : AutoLootHeavies added.
13.08.2022 14:41:27 : Beam Me Up Gerry! added.
13.08.2022 14:41:27 : Economy Reloaded! added.
13.08.2022 14:41:27 : Exhaust-less added.
13.08.2022 14:41:27 : Gerry's Junk Trunk added.
13.08.2022 14:41:27 : I Build Where I Want! added.
13.08.2022 14:41:27 : I Neeeed Sticks! added.
13.08.2022 14:41:27 : Longer Days added.
13.08.2022 14:41:27 : MaxButton Controller Support added.
13.08.2022 14:41:27 : Misc. Bits & Bobs added.
13.08.2022 14:41:27 : New Game ... At Bottom added.
13.08.2022 14:41:27 : No Time For Fishing! added.
13.08.2022 14:41:27 : Queue Everything!* added.
13.08.2022 14:41:27 : Regeneration Reloaded! added.
13.08.2022 14:41:27 : The Seed Equalizer added.
13.08.2022 14:41:27 : Thoughtful Reminders added.
13.08.2022 14:41:27 : Where's Ma' Storage! added.
13.08.2022 14:41:27 : All mods with an entry point added. This doesn't mean they'll load correctly or function if they do load.
13.08.2022 14:41:27 : Updating mod.json files for all installed mods. Information is pulled from the mods directly.
13.08.2022 14:41:32 : Add Straight To Table! added.
13.08.2022 14:41:32 : Apple Trees Enhanced! added.
13.08.2022 14:41:32 : AutoLootHeavies added.
13.08.2022 14:41:32 : Beam Me Up Gerry! added.
13.08.2022 14:41:32 : Economy Reloaded! added.
13.08.2022 14:41:32 : Exhaust-less added.
13.08.2022 14:41:32 : Gerry's Junk Trunk added.
13.08.2022 14:41:32 : I Build Where I Want! added.
13.08.2022 14:41:32 : I Neeeed Sticks! added.
13.08.2022 14:41:32 : Longer Days added.
13.08.2022 14:41:32 : Misc. Bits & Bobs added.
13.08.2022 14:41:32 : New Game ... At Bottom added.
13.08.2022 14:41:32 : No Time For Fishing! added.
13.08.2022 14:41:32 : Queue Everything!* added.
13.08.2022 14:41:32 : Regeneration Reloaded! added.
13.08.2022 14:41:32 : The Seed Equalizer added.
13.08.2022 14:41:32 : Thoughtful Reminders added.
13.08.2022 14:41:32 : Where's Ma' Storage! added.
13.08.2022 14:41:32 : All mods with an entry point added. This doesn't mean they'll load correctly or function if they do load.
13.08.2022 14:41:32 : Updating mod.json files for all installed mods. Information is pulled from the mods directly.
13.08.2022 14:43:20 : Opening config.ini for Misc. Bits & Bobs
13.08.2022 14:43:20 : Loaded config.ini for Misc. Bits & Bobs.
13.08.2022 14:43:31 : Saved changes to config.ini for Misc. Bits & Bobs.
13.08.2022 14:43:32 : Opening config.ini for Misc. Bits & Bobs
13.08.2022 14:43:32 : Loaded config.ini for Misc. Bits & Bobs.
13.08.2022 14:43:51 : Saved changes to config.ini for Misc. Bits & Bobs.
13.08.2022 14:53:28 : Successfully invoked QMod Helper entry method.
13.08.2022 14:53:28 : Assembly-CSharp.dll has been patched, (otherwise you wouldn't see this message.
13.08.2022 14:53:29 : Patch method called. Attempting to load mods.
13.08.2022 14:53:29 : Load order: 1, successfully invoked Add Straight To Table! entry method.
13.08.2022 14:53:29 : Load order: 2, successfully invoked AutoLootHeavies entry method.
13.08.2022 14:53:29 : Load order: 3, successfully invoked Exhaust-less entry method.
13.08.2022 14:53:29 : Load order: 4, successfully invoked Beam Me Up Gerry! entry method.
13.08.2022 14:53:29 : Load order: 5, successfully invoked Economy Reloaded! entry method.
13.08.2022 14:53:29 : Load order: 6, successfully invoked I Build Where I Want! entry method.
13.08.2022 14:53:29 : Gerry's Junk Trunk has been disabled in config. Skipping.
13.08.2022 14:53:29 : Load order: 8, successfully invoked Longer Days entry method.
13.08.2022 14:53:29 : Load order: 9, successfully invoked Apple Trees Enhanced! entry method.
13.08.2022 14:53:29 : Load order: 10, successfully invoked New Game ... At Bottom entry method.
13.08.2022 14:53:29 : Load order: 11, successfully invoked Misc. Bits & Bobs entry method.
13.08.2022 14:53:29 : Load order: 12, successfully invoked No Time For Fishing! entry method.
13.08.2022 14:53:29 : Load order: 13, successfully invoked Queue Everything!* entry method.
13.08.2022 14:53:29 : Load order: 14, successfully invoked Regeneration Reloaded! entry method.
13.08.2022 14:53:29 : Load order: 15, successfully invoked I Neeeed Sticks! entry method.
13.08.2022 14:53:29 : Load order: 16, successfully invoked The Seed Equalizer entry method.
13.08.2022 14:53:29 : Load order: 17, successfully invoked Thoughtful Reminders entry method.
13.08.2022 14:53:30 : Load order: 18, successfully invoked Where's Ma' Storage! entry method.
13.08.2022 14:54:26 : Successfully invoked QMod Helper entry method.
13.08.2022 14:54:27 : Assembly-CSharp.dll has been patched, (otherwise you wouldn't see this message.
13.08.2022 14:54:27 : Patch method called. Attempting to load mods.
13.08.2022 14:54:27 : Load order: 1, successfully invoked Add Straight To Table! entry method.
13.08.2022 14:54:27 : Load order: 2, successfully invoked AutoLootHeavies entry method.
13.08.2022 14:54:27 : Load order: 3, successfully invoked Exhaust-less entry method.
13.08.2022 14:54:27 : Load order: 4, successfully invoked Beam Me Up Gerry! entry method.
13.08.2022 14:54:27 : Load order: 5, successfully invoked Economy Reloaded! entry method.
13.08.2022 14:54:27 : Load order: 6, successfully invoked I Build Where I Want! entry method.
13.08.2022 14:54:27 : Load order: 7, successfully invoked Gerry's Junk Trunk entry method.
13.08.2022 14:54:27 : Load order: 8, successfully invoked Longer Days entry method.
13.08.2022 14:54:27 : Load order: 9, successfully invoked Apple Trees Enhanced! entry method.
13.08.2022 14:54:27 : Load order: 10, successfully invoked New Game ... At Bottom entry method.
13.08.2022 14:54:27 : Load order: 11, successfully invoked Misc. Bits & Bobs entry method.
13.08.2022 14:54:27 : Load order: 12, successfully invoked No Time For Fishing! entry method.
13.08.2022 14:54:27 : Load order: 13, successfully invoked Queue Everything!* entry method.
13.08.2022 14:54:27 : Load order: 14, successfully invoked Regeneration Reloaded! entry method.
13.08.2022 14:54:27 : Load order: 15, successfully invoked I Neeeed Sticks! entry method.
13.08.2022 14:54:27 : Load order: 16, successfully invoked The Seed Equalizer entry method.
13.08.2022 14:54:28 : Load order: 17, successfully invoked Thoughtful Reminders entry method.
13.08.2022 14:54:28 : Load order: 18, successfully invoked Where's Ma' Storage! entry method.
13.08.2022 15:52:15 : Opening config.ini for Exhaust-less
13.08.2022 15:52:15 : Loaded config.ini for Exhaust-less.
13.08.2022 15:52:28 : Saved changes to config.ini for Exhaust-less.
13.08.2022 15:52:33 : Opening config.ini for Where's Ma' Storage!
13.08.2022 15:52:33 : Loaded config.ini for Where's Ma' Storage!.
13.08.2022 15:52:40 : Saved changes to config.ini for Where's Ma' Storage!.
13.08.2022 15:52:47 : Opening config.ini for I Build Where I Want!
13.08.2022 15:52:47 : Loaded config.ini for I Build Where I Want!.
13.08.2022 15:52:55 : Saved changes to config.ini for I Build Where I Want!.
13.08.2022 15:53:00 : Opening config.ini for Thoughtful Reminders
13.08.2022 15:53:00 : Loaded config.ini for Thoughtful Reminders.
13.08.2022 15:53:10 : Saved changes to config.ini for Thoughtful Reminders.
13.08.2022 15:53:15 : Opening config.ini for Regeneration Reloaded!
13.08.2022 15:53:15 : Loaded config.ini for Regeneration Reloaded!.
13.08.2022 15:53:19 : Saved changes to config.ini for Regeneration Reloaded!.
13.08.2022 15:53:21 : Opening config.ini for Queue Everything!*
13.08.2022 15:53:21 : Loaded config.ini for Queue Everything!*.
13.08.2022 15:53:27 : Saved changes to config.ini for Queue Everything!*.
13.08.2022 15:53:33 : Opening config.ini for Misc. Bits & Bobs
13.08.2022 15:53:33 : Loaded config.ini for Misc. Bits & Bobs.
13.08.2022 16:36:55 : Saved changes to config.ini for Misc. Bits & Bobs.
13.08.2022 18:51:45 : Add Straight To Table! added.
13.08.2022 18:51:45 : Apple Trees Enhanced! added.
13.08.2022 18:51:45 : AutoLootHeavies added.
13.08.2022 18:51:45 : Beam Me Up Gerry! added.
13.08.2022 18:51:45 : Economy Reloaded! added.
13.08.2022 18:51:45 : Exhaust-less added.
13.08.2022 18:51:45 : Gerry's Junk Trunk added.
13.08.2022 18:51:45 : I Build Where I Want! added.
13.08.2022 18:51:45 : I Neeeed Sticks! added.
13.08.2022 18:51:45 : Longer Days added.
13.08.2022 18:51:45 : Misc. Bits & Bobs added.
13.08.2022 18:51:45 : New Game ... At Bottom added.
13.08.2022 18:51:45 : No Time For Fishing! added.
13.08.2022 18:51:46 : Queue Everything!* added.
13.08.2022 18:51:46 : Regeneration Reloaded! added.
13.08.2022 18:51:46 : The Seed Equalizer added.
13.08.2022 18:51:46 : Thoughtful Reminders added.
13.08.2022 18:51:46 : Where's Ma' Storage! added.
13.08.2022 18:51:46 : All mods with an entry point added. This doesn't mean they'll load correctly or function if they do load.
13.08.2022 18:51:46 : Updating mod.json files for all installed mods. Information is pulled from the mods directly.
13.08.2022 18:52:00 : Successfully invoked QMod Helper entry method.
13.08.2022 18:52:00 : Assembly-CSharp.dll has been patched, (otherwise you wouldn't see this message.
13.08.2022 18:52:00 : Patch method called. Attempting to load mods.
13.08.2022 18:52:00 : Load order: 1, successfully invoked Add Straight To Table! entry method.
13.08.2022 18:52:00 : Load order: 2, successfully invoked AutoLootHeavies entry method.
13.08.2022 18:52:00 : Load order: 3, successfully invoked Exhaust-less entry method.
13.08.2022 18:52:00 : Load order: 4, successfully invoked Beam Me Up Gerry! entry method.
13.08.2022 18:52:00 : Load order: 5, successfully invoked Economy Reloaded! entry method.
13.08.2022 18:52:00 : Gerry's Junk Trunk has been disabled in config. Skipping.
13.08.2022 18:52:00 : Load order: 7, successfully invoked Longer Days entry method.
13.08.2022 18:52:00 : Load order: 8, successfully invoked I Build Where I Want! entry method.
13.08.2022 18:52:00 : Load order: 9, successfully invoked Apple Trees Enhanced! entry method.
13.08.2022 18:52:00 : Load order: 10, successfully invoked New Game ... At Bottom entry method.
13.08.2022 18:52:01 : Load order: 11, successfully invoked Misc. Bits & Bobs entry method.
13.08.2022 18:52:01 : Load order: 12, successfully invoked No Time For Fishing! entry method.
13.08.2022 18:52:01 : Load order: 13, successfully invoked Queue Everything!* entry method.
13.08.2022 18:52:01 : Load order: 14, successfully invoked Regeneration Reloaded! entry method.
13.08.2022 18:52:01 : Load order: 15, successfully invoked I Neeeed Sticks! entry method.
13.08.2022 18:52:01 : Load order: 16, successfully invoked The Seed Equalizer entry method.
13.08.2022 18:52:01 : Load order: 17, successfully invoked Thoughtful Reminders entry method.
13.08.2022 18:52:01 : Load order: 18, successfully invoked Where's Ma' Storage! entry method.
14.08.2022 07:16:13 : Add Straight To Table! added.
14.08.2022 07:16:13 : Apple Trees Enhanced! added.
14.08.2022 07:16:13 : AutoLootHeavies added.
14.08.2022 07:16:13 : Beam Me Up Gerry! added.
14.08.2022 07:16:13 : Economy Reloaded! added.
14.08.2022 07:16:13 : Exhaust-less added.
14.08.2022 07:16:13 : Gerry's Junk Trunk added.
14.08.2022 07:16:13 : I Build Where I Want! added.
14.08.2022 07:16:13 : I Neeeed Sticks! added.
14.08.2022 07:16:13 : Longer Days added.
14.08.2022 07:16:13 : Misc. Bits & Bobs added.
14.08.2022 07:16:13 : New Game ... At Bottom added.
14.08.2022 07:16:13 : No Time For Fishing! added.
14.08.2022 07:16:13 : Queue Everything!* added.
14.08.2022 07:16:13 : Regeneration Reloaded! added.
14.08.2022 07:16:13 : The Seed Equalizer added.
14.08.2022 07:16:13 : Thoughtful Reminders added.
14.08.2022 07:16:14 : Where's Ma' Storage! added.
14.08.2022 07:16:14 : All mods with an entry point added. This doesn't mean they'll load correctly or function if they do load.
14.08.2022 07:16:14 : Updating mod.json files for all installed mods. Information is pulled from the mods directly.
