### ISSUE TITLE
[BUG] Save now - Game cannot load the saves with addon On.

### ISSUE THREAD

**Issue by DarkInos** [p1xel8ted/GYK-Mods-QMod#25]
**Requirements**
- Please include a screenshot of QMod Manager Reloaded so that I can see what mods you have installed and their load order.
- I have tried to move it among the lines.. to first last middle.. did not do anything.
![QMod](https://user-images.githubusercontent.com/6153995/185788622-b144adf4-80a7-4ad0-89e6-109739bf2926.png)

**Required Logs**
Please delete both logs and test the game again so it generates fresh logs with only relevant entries.
[Player.log](https://github.com/p1xel8ted/GYK-Mods-QMod/files/9388984/Player.log)
[qmod_reloaded_log.txt](https://github.com/p1xel8ted/GYK-Mods-QMod/files/9388983/qmod_reloaded_log.txt)

**What mod are you reporting a bug for?**
- Mod - Save Now
- Version - 2,4
- Where did you download it from [NexusMods](https://www.nexusmods.com/graveyardkeeper/mods/41?tab=files)

**Describe the bug**
Game froze the pc few times.. no big problem.. but today.. it froze again after few hours and when I tried to load back, game could not sync saves for some reason.
And after game started:
![Savespot](https://user-images.githubusercontent.com/6153995/185788749-fe606ddc-13b6-4590-8ca4-92c16bda032c.png)
Saves gone.. not even able to get "New game" so I have tried to restart game, did not work.
Turned off all addons = worked.

So I have used my brain and guessed.. that if I do not see saves.. it will have something to do with "Save Now" mod.
So I have turned only that one and saves were back there, but only those that were done in the bed classic way (so.. hours and hours of gametime lost, cause I'm idiot to do frequent sleep if I do not have to).
I have tried to delete all saves and turn on game with addon on and did nothing..

**To Reproduce**
Detailed steps to reproduce the behavior:
I do not know how to "reproduce" it on the other device.. I guess something happened when pc froze during saving I guess?
Right now.. just turning on game with the mod = seeing the picture above, turning off..

**Expected behavior**
I would expect to see normal saves + the one done by addon.

**Screenshots/Video**
With mod on:
![Savespot](https://user-images.githubusercontent.com/6153995/185788749-fe606ddc-13b6-4590-8ca4-92c16bda032c.png)

With mod off:
![Savespot2](https://user-images.githubusercontent.com/6153995/185789391-7a5712a7-fc51-43f3-a7a1-62694f8569bf.png)

Last 2 saves.
The one for 21.8 (11:45) is from today, that game does not register, so I guess done with mod.
The one for 20.8 (22:44) is from yesterday, classic bed = works without mods.
[Graveyard KeeperSaves.zip](https://github.com/p1xel8ted/GYK-Mods-QMod/files/9389009/Graveyard.KeeperSaves.zip)

**Desktop (please complete the following information):**
- Windows version - Windows 10
- Windows language - Czech
- Game language - English
- Game platform - PC - Steam

**Additional context**
Also I see weird times on saves anyway.. like all the saves done by "K" were not recorded I guess? Too much time between saves..
I used K quite often after first pc freeze, and had addon set to save every hour..
![Savespot3](https://user-images.githubusercontent.com/6153995/185789592-854c570e-83cf-482c-8f1d-55be513bb0c3.png)

**Comment by p1xel8ted** [comment]
- Pressing K will save to the currently loaded save; it won't make a new one. 
- All those with autosave and the time and date in them are from the game autosaving (not you pressing K).

Your error log indicates that the JSON files are empty (the *.info files) - if you open them in Notepad, is there text?

**Comment by DarkInos** [comment]
> Your error log indicates that the JSON files are empty (the *.info files) - if you open them in Notepad, is there text? The files are generated by the game, not the mod. It also uses those files to read the save game info - if it's blank, it won't load.
Do you mean autosave.xxxx.info?
Actually.. the last save (from today) is empty, the other ones are filled with
{"stats":"(wskull)310  (cross)66","real_time":"22:44, 20 Aug 2022","game_time":108.86592102050781,"version":1.4049999713897706}
Type of the text...
So I could guess that the last save was corrupted when it crashed my pc and is irreversible, right?..

I guess I can .. eh live with that 🤷  but it does not explain why I cannot use the mod now at all.
Even if I delete all the saves and turn off Steam - Sync,
Game will not let me load any of the saves, or create new game with the "Save now" mod turned on.

That is still puzzling.. last thing I could do is probably to reinstall game completely I guess, if there is nothing wrong with the mod. That is still weird tho.. I have even reinstalled the mod to get "a clean slate" with it.. and same problem is there..
Game is ok by the standard from the steam check... really weird.

**Comment by DarkInos** [comment]
Eh I clicked by that closed by mistake.. but well I'm not sure if you can help anymore if it is some corrupted thing on my part only..

**Comment by p1xel8ted** [comment]
You can copy that text into the other saves to get them working (they will all look the same in the list until you load into the game and it updates them).

Also, if you're removing the files with the game closed, Steam Cloud Sync will reload them when you launch the game. Only make changes to that folder if the game is running (at the menu).

**Comment by DarkInos** [comment]
I will try reinstalling game and re-modding it again. I just do not have time currently to play with it.
The game just does not work with "Save now" addon. Even with save sync off, saves deleted, no error message nothing.

**Comment by p1xel8ted** [comment]
> I will try reinstalling game and re-modding it again. I just do not have time currently to play with it. The game just does not work with "Save now" addon. Even with save sync off, saves deleted, no error message nothing.

Have you tried setting "DontPruneSaves=true" to false?
And have you tried with just SaveNow, no other mods?

**Comment by p1xel8ted** [comment]
Can you zip up your entire QMod directory, and attach it.
