### ISSUE TITLE
[BUG] Wheres Ma Storage - shared inventory bug

### ISSUE THREAD

**Issue by esnaksy** [p1xel8ted/GYK-Mods-QMod#27]
**Required Logs**
[Player.log](https://github.com/p1xel8ted/GYK-Mods-QMod/files/9768373/Player.log)
[qmod_reloaded_log.txt](https://github.com/p1xel8ted/GYK-Mods-QMod/files/9768372/qmod_reloaded_log.txt)

**What mod are you reporting a bug for?**
- Mod: Wheres Ma Storage
- Version: 1.9
- Where did you download it from: nexusmods.com

**Describe the bug**
- if SharedInventory flat is true game occasionally crashes when trying to open a trade with an npc
- tools cant be added to grinding stone at home while equipped (minor issue)

**To Reproduce**
Start a new game, talk to Horadric or Krezvold or any other npc who trades, open trade
Sometimes crashes (first issue)
Takes too long to open (second issue)
And "Chest (Wilderness)" appears on the list, which I can sell items from (which I dont have) (third issue)

**Screenshots/Video**
![2022-10-12_214709](https://user-images.githubusercontent.com/115662905/195437411-678229c1-e35d-4bde-80e1-1d416a198563.png)
![2022-10-12_214842](https://user-images.githubusercontent.com/115662905/195437368-fce90ea5-7b73-4ddd-948f-393c872c4ac2.png)
![2022-10-12_230133](https://user-images.githubusercontent.com/115662905/195437303-c11507df-af33-40d0-bfe5-48d8594b6851.png)
![2022-10-12_230122](https://user-images.githubusercontent.com/115662905/195437312-c847a67a-6ec5-46be-9cd5-eec73c012797.png)
![2022-10-12_223607](https://user-images.githubusercontent.com/115662905/195437320-dd07fc30-2fcb-4780-b5fe-577d17e6324f.png)

**Desktop (please complete the following information):**
- Windows 10 Enterprise 21H2 - Eng x64
- Game language - Eng

**Comment by p1xel8ted** [comment]
Does it occur if you have ONLY Where's Ma Storage active?

**Comment by esnaksy** [comment]
I started a new game with only Where's Ma Storage active and CacheEligibleInventories=**false**
This is the result with Horadrick and Krezvold, only one chest in wilderness  BUT I can repair tools that are equipped. 

![Untitled](https://user-images.githubusercontent.com/115662905/197386368-4f6f794b-803a-4fe7-a4f8-617cc0396284.jpg)

If I set CacheEligibleInventories=**true** result is same as first post, like many chests in wilderness and CANT repair equipped tools

**Comment by p1xel8ted** [comment]
Fixed in 2.0
