### ISSUE TITLE
[BUG] Can't increase/decrease amount of multicrafts (always maxes out)

### ISSUE THREAD

**Issue by HeianMightbreeze** [p1xel8ted/GYK-Mods-QMod#28]
**Requirements**
1. Queue Everything| 1.9.9| p1xel8ted
2. Thoughtfull Reminders| 2.1| p1xel8ted

**Required Logs**
Please delete both logs and test the game again so it generates fresh logs with only relevant entries.
- C:\Users\<username>\AppData\LocalLow\Lazy Bear Games\Graveyard Keeper\Player.log
- ...\Graveyard Keeper\qmod_reloaded_log.txt

**What mod are you reporting a bug for?**
1. Queue Everything| 1.9.9| p1xel8ted
ModNexus

**Describe the bug**
Can't increase/decrease amount of multicrafts (always maxes out)

**To Reproduce**
happens all the time 100%

**Expected behavior**
buttons on the sides like in the picture on ModsNexus.

**Screenshots/Video**

**Desktop (please complete the following information):**
- Windows 10 Home
- Windows language: Swedish
- Game language: English
- Game platform: PC/Steam

**Additional context**
- Add any other context about the problem here.

**Comment by HeianMightbreeze** [comment]
[qmod_reloaded_log.txt](https://github.com/p1xel8ted/GYK-Mods-QMod/files/9792328/qmod_reloaded_log.txt)
[Player.log](https://github.com/p1xel8ted/GYK-Mods-QMod/files/9792331/Player.log)

**Comment by p1xel8ted** [comment]
I can't replicate this. The buttons in the screenshot are from a mod called MaxButtons, but the normal button works as intended even without that mod enabled. Clicking works, pressing the Left/Right arrows works, and using the controller buttons works.
