### ISSUE TITLE
[Bug] Graves stacking even with option disabled

### ISSUE THREAD

**Issue by truehiddenevil** [p1xel8ted/GYK-Mods-QMod#30]
Requirements

    Where's Ma' Storage!| 1.9| p1xel8ted

Required Logs

    [Player.log](https://github.com/p1xel8ted/GYK-Mods-QMod/files/9862329/Player.log) (I looked and couldn't find anything unusual)
    qmod_reloaded_log.txt has nothing unexpected/unusual (only 4 lines)

What mod are you reporting a bug for?

    Where's Ma' Storage!| 1.9| p1xel8ted

Describe the bug

    Graves will stack even if the associated option is disabled

To Reproduce

    have EnableGraveItemStacking=false and in any manner acquire 2 of the same grave item

Expected behavior

    graves don't stack when option is false

Screenshots/Video

Desktop (please complete the following information):

    Windows 10 Home
    Windows language: English
    Game language: English
    Game platform: PC/Steam

Additional context

    managed to fix the issue locally by patching the dll
    i patched the WheresMaStorage.MainPatcher.DropResGameObjectCollectDrop to ignore the config and force a 1
    replaced instruction 13 ldsfld with nop and instruction 14 ldfld with ldc.i4.1
    EDIT:fixed formating

**Comment by p1xel8ted** [comment]
[WheresMaStorage.v191.zip](https://github.com/p1xel8ted/GYK-Mods-QMod/files/9893208/WheresMaStorage.v191.zip)

Stack sizes are adjusted on game load - the particular place you patched is actually intended for when removing the grave item from graves. When the size is greater than 1, they fail to remove, so I had to make it set the size to 1, remove the grave item, and set the size back up. 

Try the attached one. There was no config there, so it should honour your settings now.

**Comment by truehiddenevil** [comment]
Seems to be fixed as far as I can tell
