### ISSUE TITLE
[BUG] Items placed in chest do not disappear when sold

### ISSUE THREAD

**Issue by truehiddenevil** [p1xel8ted/GYK-Mods-QMod#32]
**Requirements**
    Just Gerry's Junk Trunk v1.6

**Required Logs**
    applicable part
```
Exception: No input
  at ParadoxNotion.Serialization.FullSerializer.fsResult.AssertSuccess () [0x0000e] in <c6b68a8143944cc584689e69161d0c41>:0 
  at ParadoxNotion.Serialization.FullSerializer.fsJsonParser.Parse (System.String input) [0x00009] in <c6b68a8143944cc584689e69161d0c41>:0 
  at ParadoxNotion.Serialization.JSONSerializer.Deserialize (System.Type type, System.String serializedState, System.Collections.Generic.List`1[T] objectReferences, System.Object deserialized) [0x00058] in <c6b68a8143944cc584689e69161d0c41>:0 
  at ParadoxNotion.Serialization.JSONSerializer.Deserialize[T] (System.String serializedState, System.Collections.Generic.List`1[T] objectReferences, T deserialized) [0x00000] in <c6b68a8143944cc584689e69161d0c41>:0 
  at NodeCanvas.Framework.Blackboard.UnityEngine.ISerializationCallbackReceiver.OnAfterDeserialize () [0x00017] in <c6b68a8143944cc584689e69161d0c41>:0 
UnityEngine.Object:Internal_CloneSingle(Object)
UnityEngine.Object:Instantiate(WorldGameObject)
GerrysJunkTrunk.MainPatcher:RefreshVendors()
GerrysJunkTrunk.MainPatcher:GetItemEarnings(Item)
GerrysJunkTrunk.BaseItemCellGuiInitTooltipsPatch:Prefix(InventoryPanelGUI&, BaseItemCellGUI&)
InventoryPanelGUI:InventoryPanelGUI.OnItemOver_Patch2(InventoryPanelGUI, InventoryWidget, BaseItemCellGUI)
<>c__DisplayClass46_2:<DoOpening>b__5(BaseItemCellGUI)
InventoryWidget:OnItemOver(BaseItemCellGUI)
BaseItemCellGUI:OnOver(Boolean)
BaseItemCellGUI:OnMouseOvered()
EventDelegate:Execute()
EventDelegate:Execute(List`1)
UIEventTrigger:OnHover(Boolean)
UnityEngine.GameObject:SendMessage(String, Object, SendMessageOptions)
UICamera:Notify(GameObject, String, Object)
UICamera:set_hoveredObject(GameObject)
UICamera:ProcessMouse()
UICamera:ProcessTouches()
UICamera:ProcessEvents()
UICamera:Update()

```

**What mod are you reporting a bug for?**
    Gerry's Junk Trunk
    v1.6 
    Nexus

**Describe the bug**
    Items placed in chest do not disappear when sold

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Place any item in Gerry's Junk Trunk
2. Wait till sell triggers
3. Item is still there

**Expected behavior**
    Items disappear when sold

**Desktop (please complete the following information):**
    Windows 10 Home
    OS English
    Game English
    Steam

**Comment by p1xel8ted** [comment]
- Have you been selling this item(s) constantly?
- Is it one particular item or all items?

**Comment by truehiddenevil** [comment]
It seems to be any item at all. I've tested red and blue potions, stone pieces and gravestones. You get the money just the items stay there. Here are my full logs from testing the other 2 fixes. The only obvious error I can find is a new one referring to MiscBitsAndBobs as a IndexOutOfRangeException.

[Player.log](https://github.com/p1xel8ted/GYK-Mods-QMod/files/9894060/Player.log)
[qmod_reloaded_log.txt](https://github.com/p1xel8ted/GYK-Mods-QMod/files/9894061/qmod_reloaded_log.txt)

**Comment by truehiddenevil** [comment]
Found out what was causing the MiscBitsAndBobs error. It was having too many tech points from before the mod was installed or added via save editor. The error stopped after the tech points were updated. EX: getting more tech points or spending some

**Comment by p1xel8ted** [comment]
Yeah MBB has an issue when converting the display value to a decimal, doesn't seem to effect anything so I've never bothered to look into it much further.

When you open the trunk, does it say gerrys trunk with how many vendors you know? And does Gerry spawn to sell the items?

**Comment by truehiddenevil** [comment]
Yes it says "Gerry's Junk Trunk (T3) - 18 vendo" it gets cut off. The vendor number changes sometimes. I think I've seen it at 19 too. Gerry does not spawn as I have that option turned off. I'll try it with him enabled.

**Comment by truehiddenevil** [comment]
Yep It works properly with him enabled

**Comment by p1xel8ted** [comment]
> Yep It works properly with him enabled

Ok cheers, I've obviously cooked it somewhere then haha. All good, easy enough - cheers for testing that.

**Comment by truehiddenevil** [comment]
Works fine now with Gerry disabled.
