### ISSUE TITLE
[BUG] Queue Everything mod breaks Carpenter perk

### ISSUE THREAD

**Issue by jcollum** [p1xel8ted/GYK-Mods-QMod#33]
**Requirements**

After uninstalling: 

![image](https://user-images.githubusercontent.com/704514/199147528-825654b1-aa92-44f2-a3c1-fd096d166b39.png)

**Required Logs**

[Player.log](https://github.com/p1xel8ted/GYK-Mods-QMod/files/9906345/Player.log)

- ...\Graveyard Keeper\qmod_reloaded_log.txt -- this file is not in \AppData\LocalLow or any subfolder of it. 

**What mod are you reporting a bug for?**

Queue Everything-57-1-9-9-1661423061

https://www.nexusmods.com/graveyardkeeper/mods/57?tab=posts&BH=1

**Describe the bug**

Breaks Carpenter perk. After trying this out I noticed my circular saw was running at like 1/3rd speed. Carpenter perk appeared to be broken. So I uninstalled with QMod Mgr and restarted the game. Got this: https://imgur.com/mT4A9kg. Note: I didn't disable it, I fully removed it from QMM. But after uninstalling it does seem like the saw is working correctly again. The mod manager should be updating that title screen though. 

**To Reproduce**

Install mod. Start game. Use circular saw while having the carpenter perk.

**Expected behavior**

Mod does not break the perk. 

**Desktop (please complete the following information):**

Win 10, English

**Additional context**
- Add any other context about the problem here.

**Comment by p1xel8ted** [comment]
- If you have MakeEverythingAuto set to true, the crafts are slower. This is intended.
- Just uninstalling QMR doesn't remove the patch that enables mods to be injected, hence why the title screen still shows the patched version.
