### ISSUE TITLE
Impossible to remove barrel

### ISSUE THREAD

**Issue by Jtk310** [p1xel8ted/GYK-Mods-QMod#35]
I accidentally placed a barrel where the workbench goes in the soul lab area, but cant remove it. Is there any way I can remove the barrel? I wasn't sure where to ask this so I hope this is the correct location
Thank you!

**Comment by p1xel8ted** [comment]
Here is fine, otherwise the Discord channel (link can be found on mod description pages on Nexus)

As for your problem, by barrell do you mean the wine barrels? Is it an access issue? Player can't fix for example or it doesn't let you select it when in Remove mode?

**Comment by Jtk310** [comment]
![image](https://user-images.githubusercontent.com/2846469/205524809-89c79a72-e992-438a-aab7-51404e41705e.png)

Thank you for the reply! it's the sort of barrel that goes in the talking skull tavern when you're improving. I like their look and have been adding those around a few places on an older save and noticed when I went to do the soul lab stuff that I had messed it up! The cursor turns red in remove mode when over the barrel in question (tried to show the cursor in the screenshot)

**Comment by p1xel8ted** [comment]
Probably need to write something to allow force deletion of items for this one.

**Comment by Jtk310** [comment]
So far it doesn't seem to block me from any progress (gathering last 3 shards now, will update on if it blocks anything other than convenience) and even if it did it's an old save anyway so no need to write anything on my account 😄 
Is it possible to place that organ workbench (https://graveyardkeeper.fandom.com/wiki/Organ_Workbench) with the mod? I didnt see it in the list but thought it might have a different name
Thanks!

**Comment by p1xel8ted** [comment]
No resolution at this time unfortunately.
