### ISSUE TITLE
[BUG] Wheres Ma Storage issue with the Trader's Barn

### ISSUE THREAD

**Issue by RadMage1** [p1xel8ted/GYK-Mods-QMod#36]
With the Wheres Ma Storage (2.02) mod installed I wasn't able to build the pallets in the Trader's barn.  It wasn't recognizing the marketing points as an ingredient. Showing 0 available even though I should have had 2 at the time. I just disabled the mod before building the pallets and turned it on again afterwards as a workaround. Only issue I've encounter so far.

Using QMod Manager reloaded 1.0.8272.35378.  

Thanks for the great mods!

RAD

**Comment by p1xel8ted** [comment]
[WheresMaStorage.v203.zip](https://github.com/p1xel8ted/GYK-Mods-QMod/files/10328340/WheresMaStorage.v203.zip)

Try this and let me know please.

**Comment by RadMage1** [comment]
No, that didn't seem to fix it. Happens when "SharedInventory=true". If I turn off shared inventory it works fine.  I had a similar problem with the refugee camp. With  when you want to "craft" a New Refugee, the game is not recognizing "the free place" crafting resource.

Neither of these are physical items you can have in an inventory which sets them apart.

Thanks!

**Comment by RadMage1** [comment]
OK, I think it is breaking when the game tries to add to those resource pools. I loaded a save where I had "shareinventory=false" 
 when I previously played and "the free place" resource was available and it is still there and working.  You get these from building the tents in the refugee camp.

I hope I'm explaining it correctly.  I will try a test with the barn to see if I get the same results.

**Comment by p1xel8ted** [comment]
This fix was primarily geared towards the refugee camp, I was hoping it would fix the trader as well. Can you post the save game?

**Comment by RadMage1** [comment]
Let me test some more first.   When I reloaded the save the resource was showing correctly and I added some flyers and it appeared to update correctly.  Maybe something is wrong when its zero at the start?  I am going to start a new save and doubled check.  If I have the issue, I will send you that save which would be a better test.

**Comment by RadMage1** [comment]
OK, I started a new game and the barn is working fine now. I haven't reached the point where I can test the camp much.  I'll follow up later.

Thanks!

**Comment by RadMage1** [comment]
The camp was showing zero for "free place" until I saved and reloaded. Only issue I've had.

**Comment by p1xel8ted** [comment]
> The camp was showing zero for "free place" until I saved and reloaded. Only issue I've had.

Ok, I've added an extra step that forces a reload of inventories if you're interacting with either of those particular build desks, just in case. The market points and refugee happiness are in fact items stored in an inventory, it's just not interactable with by the player. 

The way I was excluding the Refugee camp storage (for the "IncludeRefugeeDepot" option) was inadvertently excluding the happiness. Not sure why the market was affected.
