### ISSUE TITLE
[BUG] <I Build Where I Wantm>

### ISSUE THREAD

**Issue by Yolkapoli** [p1xel8ted/GYK-Mods-QMod#37]
I am the third with the following problem: the Refuge has been broken. It is not possible to add more residents. Your mod seemed to be something cool as always, but this time it has broken two games, I hope this has a solution.

**Comment by p1xel8ted** [comment]
I need a save game that has the issue.

**Comment by Yolkapoli** [comment]
It is a problem with the phoning mod. Either way, I send this if it's helpful. Thank you for your valuable time, man.
[Yolkapoli.zip](https://github.com/p1xel8ted/GYK-Mods-QMod/files/10321202/Yolkapoli.zip)

**Comment by p1xel8ted** [comment]
[WheresMaStorage.v203.zip](https://github.com/p1xel8ted/GYK-Mods-QMod/files/10328342/WheresMaStorage.v203.zip)

Try this and let me know please.

**Comment by p1xel8ted** [comment]
Confirmed fixed elsewhere

**Comment by Yolkapoli** [comment]
The problem persists and now ruins the mission of the cathedral.

**Comment by p1xel8ted** [comment]
It doesn't persist. Had multiple confirmations it's fixed. Check your config etc. Otherwise jump on the Discord.
