### ISSUE TITLE
[BUG] WheresMaStorage: Refugee Camp adding new members

### ISSUE THREAD

**Issue by RunAge** [p1xel8ted/GYK-Mods-QMod#39]
**Requirements**
- Please include a screenshot of QMod Manager Reloaded so that I can see what mods you have installed and their load order.
![obraz](https://user-images.githubusercontent.com/11584396/210137295-a2157c52-93c1-41c2-9304-2f87d7567e6c.png)
Load order in qmod_reloaded_log.txt

**Required Logs**
Please delete both logs and test the game again so it generates fresh logs with only relevant entries.
- [Player.log](https://github.com/p1xel8ted/GYK-Mods-QMod/files/10327384/Player.log)
- [qmod_reloaded_log.txt](https://github.com/p1xel8ted/GYK-Mods-QMod/files/10327385/qmod_reloaded_log.txt)

**What mod are you reporting a bug for?**
- Mod: WheresMaStorage
- Version: 2.0.2
- Where did you download it from: NexusMods

**Describe the bug**
- When mod is enabled in refugee camp count of beds needed to add new member show 0/1. After disabling mod number show correct value

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Go to 'refugee camp'
2. Click on 'building table after getting quest for extending for new members'
3. See error

**Expected behavior**
- Show correct value of beds/places for refugee

**Screenshots/Video**
- I don't have now but after progressing to next extenstion of refugee members I will add one

**Desktop (please complete the following information):**
- Windows version: 10
- Windows language: English
- Game language: English
- Game platform: GOG

**Additional context**

**Comment by p1xel8ted** [comment]
[WheresMaStorage.v203.zip](https://github.com/p1xel8ted/GYK-Mods-QMod/files/10328339/WheresMaStorage.v203.zip)

Try this and let me know please.

**Comment by RunAge** [comment]
Fixed :D
