### ISSUE TITLE
Not really sure how to describe it

### ISSUE THREAD

**Issue by Suicaedere** [p1xel8ted/GYK-Mods-QMod#40]
So, uhh.. This is a thing that happened.
I was doing something in a crafting menu, last night, when the chest prompt came up. It froze my game, had to roll back ~2 days and the first night the chest prompt came up (despite it rolling me back to before I had one built) and it came up like this. The buttons don't work, and it's seemingly now hardlocked my game. I might be able to get past it if I recreate my steps to get the chest in time, but I think I'd rather just restart.

[image](https://user-images.githubusercontent.com/111821290/210456877-83d2c72d-3407-47ec-bce0-24f436494e09.png)

**Comment by p1xel8ted** [comment]
That looks like a test window from the devs. Certainly not part of my mods. What mods were using at the time, and is there any messages in the log files?

**Comment by Suicaedere** [comment]
Other than grave changes, which basically lets you design the graveyard for cosmetics rather than just being optimal, it's all your mods. The only time that I can recall seeing that window pop up is from the Gerry's Junk Trunk, which I think caused an issue/crash (may have been build anywhere, or a combination between them, as I was in that menu when the pop up interrupted me) previously. Not sure why it would activate when I didn't have one built though, although I had to alt f4 from both crashes so maybe something went wonky from that?


![image](https://user-images.githubusercontent.com/111821290/210474948-4cb11eb0-4032-478c-b530-77f0b766ff80.png)

**Comment by p1xel8ted** [comment]
What's the one that has no data, number 12. Should be able to double click the line to open the folder. Also, make sure the game is version 1.405

**Comment by p1xel8ted** [comment]
Unable to reproduce.
