### ISSUE TITLE
[BUG] <Where's Ma Storage! - Refugee bed bug>

### ISSUE THREAD

**Issue by Tyrnox** [p1xel8ted/GYK-Mods-QMod#41]
**Requirements**
- Please include a screenshot of QMod Manager Reloaded so that I can see what mods you have installed and their load order.
Load order in logs [no problems here]

**Required Logs**
Please delete both logs and test the game again so it generates fresh logs with only relevant entries.
- C:\Users\<username>\AppData\LocalLow\Lazy Bear Games\Graveyard Keeper\Player.log
I don't see player.log anywhere in said folder or it's subfolders

- ...\Graveyard Keeper\qmod_reloaded_log.txt
1/5/2023 3:23:47 PM : Successfully invoked QMod Helper entry method.
1/5/2023 3:23:47 PM : Assembly-CSharp.dll has been patched, (otherwise you wouldn't see this message.
1/5/2023 3:23:47 PM : Patch method called. Attempting to load mods.
1/5/2023 3:23:47 PM : Longer Days has been disabled in config. Skipping.
1/5/2023 3:23:47 PM : Load order: 1, successfully invoked Add Straight To Table! entry method.
1/5/2023 3:23:47 PM : Load order: 2, successfully invoked Beam Me Up Gerry! entry method.
1/5/2023 3:23:47 PM : Load order: 3, successfully invoked Auto-Loot Heavies! entry method.
1/5/2023 3:23:47 PM : Load order: 4, successfully invoked Give Me Moar! entry method.
1/5/2023 3:23:47 PM : Load order: 5, successfully invoked FasterCraft Reloaded! entry method.
1/5/2023 3:23:47 PM : Load order: 7, successfully invoked Economy Reloaded! entry method.
1/5/2023 3:23:47 PM : Load order: 8, successfully invoked No Time For Fishing! entry method.
1/5/2023 3:23:47 PM : Load order: 9, successfully invoked Save Now! entry method.
1/5/2023 3:23:47 PM : Load order: 10, successfully invoked Regeneration Reloaded! entry method.
1/5/2023 3:23:48 PM : Load order: 11, successfully invoked Gerry's Junk Trunk entry method.
1/5/2023 3:23:48 PM : Load order: 12, successfully invoked The Seed Equalizer entry method.
1/5/2023 3:23:48 PM : Load order: 13, successfully invoked Exhaust-less entry method.
1/5/2023 3:23:48 PM : Load order: 14, successfully invoked Queue Everything!* entry method.
1/5/2023 3:23:48 PM : Load order: 17, successfully invoked Ultra Wide entry method.
1/5/2023 3:23:48 PM : Load order: 18, successfully invoked Thoughtful Reminders entry method.
1/5/2023 3:23:48 PM : Load order: 19, successfully invoked Where's Ma' Storage! entry method.
1/5/2023 3:23:48 PM : Load order: 20, successfully invoked Where's Ma' Points! entry method.

**What mod are you reporting a bug for?**
- Mod: Where's Ma Storage!
- Version: 2.0.2
- Where did you download it from: Nexus

**Describe the bug**
- Beds won't appear on the list and additional refugees can't be "crafted" until mod is disabled. No crashes or logs.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Run game with mod
2. Install tent in refugee camp
3. Build tent
4. Check available constructions, the beds won't appear on the list.

**Expected behavior**
- Beds won't appear on the list and additional refugees can't be "crafted" until mod is disabled.
- When mod is disabled, game becomes laggy, might be because there were too many storages that have been filled over max.

**Screenshots/Video**
- If applicable, add screenshots to help explain your problem or provide a YouTube link.
N/A

**Desktop (please complete the following information):**
- Windows 11
- English
- Game language : English
- Game platform : Steam

**Additional context**
- Add any other context about the problem here.
N/A

**Comment by p1xel8ted** [comment]
Update the mod.
