### ISSUE TITLE
[BUG] <Burger Making Infinite loop on cooking table>

### ISSUE THREAD

**Issue by thelastman112** [p1xel8ted/GYK-Mods-QMod#43]
**Requirements**
- Please include a screenshot of QMod Manager Reloaded so that I can see what mods you have installed and their load order.
![image](https://user-images.githubusercontent.com/75193587/212545081-ed95105d-a6d0-4928-99ea-9049ad4a9acb.png)

**Required Logs**
Please delete both logs and test the game again so it generates fresh logs with only relevant entries.
- C:\Users\<username>\AppData\LocalLow\Lazy Bear Games\Graveyard Keeper\Player.log
https://pastebin.com/sGXsMrLT
- ...\Graveyard Keeper\qmod_reloaded_log.txt
https://pastebin.com/kKcMDSvC

**What mod are you reporting a bug for?**
- Mod: Give Me Moar! 
- Version: 1.2.3
- Where did you download it from Nexus

**Describe the bug**
- A clear and concise description of what the bug is.
Burger Bugged on Cooking table. Can't stop making it, basically give me an infinite loop of making the burger, and can't cancel it either except by quitting the game and launching it without the said mod.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Go To the cooking table and made the burger, use any of the onions I have (which are silver and gold while making it)
2. Press F to work on it and the bug happens 

**Expected behavior**
- A clear and concise description of what you expected to happen.
What I expected was making the normal amount of burgers it said on the UI of the game which is 4 and not having the infinite loop

**Screenshots/Video**
- If applicable, add screenshots to help explain your problem or provide a YouTube link.
![image](https://user-images.githubusercontent.com/75193587/212545196-d375eb0e-8d02-4f9b-a01e-f04cd298da1d.png)

**Desktop (please complete the following information):**
- Windows version: windows 10
- Windows language: English
- Game language: English
- Game platform: Pirated (u can hate me cause I'm a poor kid but I try saving some money to buy the game)

**Additional context**
- Add any other context about the problem here.
Sorry for the bad English, its not my main language (From South East Asia)

**Comment by p1xel8ted** [comment]
Fixed, update being posted momentarily.
