### ISSUE TITLE
[BUG] Desk infinity crafting 

### ISSUE THREAD

**Issue by Milliardo-V** [p1xel8ted/GYK-Mods-QMod#45]
What mod are you reporting a bug for?
- I do not know what is the mod causing the bug
- nexusmods

**Describe the bug**
- Desk don't stop the crafting for chapters or prayers.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Go to the desk try to craft chapters or prayers.
2. Click on craft, exit the menu and hold "Y"
4. It keeps crafting the item does not use the material but spends the energy, and I can't cancel the recipe.   

**Expected behavior**
- Normal craft

- Windows 10 
- Windows English 
- Game English 
- Game Pc Steam

![QMod Manager](https://user-images.githubusercontent.com/80431461/213031208-2ca40e28-664d-4203-8dc7-59caae3bcf9a.jpg)
[Player.log](https://github.com/p1xel8ted/GYK-Mods-QMod/files/10440031/Player.log)
[qmod_reloaded_log.txt](https://github.com/p1xel8ted/GYK-Mods-QMod/files/10440032/qmod_reloaded_log.txt)

**Comment by p1xel8ted** [comment]
Resolved in Give Me Moar Update. Update your mods.
