### ISSUE TITLE
[BUG] <detailed, but to the point issue description>

### ISSUE THREAD

**Issue by Greenblyat** [p1xel8ted/GYK-Mods-QMod#46]

**Comment by Greenblyat** [comment]
1/19/2023 6:42:55 PM : Successfully invoked QMod Helper entry method.
1/19/2023 6:42:55 PM : Assembly-CSharp.dll has been patched, (otherwise you wouldn't see this message.
1/19/2023 6:42:55 PM : Patch method called. Attempting to load mods.
1/19/2023 6:42:55 PM : Load order: 1, successfully invoked Add Straight To Table! entry method.
1/19/2023 6:42:55 PM : Load order: 2, successfully invoked Apple Trees Enhanced! entry method.
1/19/2023 6:42:55 PM : Load order: 3, successfully invoked Auto-Loot Heavies! entry method.
1/19/2023 6:42:55 PM : Load order: 4, successfully invoked Beam Me Up Gerry! entry method.
1/19/2023 6:42:55 PM : Load order: 5, successfully invoked Bring Out Yer Dead! entry method.
1/19/2023 6:42:55 PM : Load order: 6, successfully invoked Economy Reloaded! entry method.
1/19/2023 6:42:55 PM : Load order: 7, successfully invoked FasterCraft Reloaded! entry method.
1/19/2023 6:42:55 PM : Load order: 8, successfully invoked ItemDescriptionElement entry method.
1/19/2023 6:42:56 PM : Load order: 9, successfully invoked Gerry's Junk Trunk entry method.
1/19/2023 6:42:56 PM : Load order: 10, successfully invoked AlwaysShowExperienceBar entry method.
1/19/2023 6:42:56 PM : Load order: 11, successfully invoked I Build Where I Want! entry method.
1/19/2023 6:42:56 PM : Load order: 12, successfully invoked  entry method.
1/19/2023 6:42:56 PM : Load order: 13, successfully invoked Longer Days entry method.
1/19/2023 6:42:56 PM : Load order: 14, successfully invoked New Game ... At Bottom entry method.
1/19/2023 6:42:56 PM : Load order: 15, successfully invoked Sprint Reloaded entry method.
1/19/2023 6:42:56 PM : Load order: 16, successfully invoked MaxButton entry method.
1/19/2023 6:42:56 PM : Load order: 17, successfully invoked No Time For Fishing! entry method.
1/19/2023 6:42:56 PM : Load order: 18, successfully invoked Pray The Day Away! entry method.
1/19/2023 6:42:56 PM : Load order: 19, successfully invoked Queue Everything!* entry method.
1/19/2023 6:42:56 PM : Load order: 20, successfully invoked Regeneration Reloaded! entry method.
1/19/2023 6:42:56 PM : Load order: 21, successfully invoked Save Now! entry method.
1/19/2023 6:42:56 PM : Load order: 22, successfully invoked Thoughtful Reminders entry method.
1/19/2023 6:42:56 PM : Load order: 23, successfully invoked The Seed Equalizer entry method.
1/19/2023 6:42:56 PM : Load order: 24, successfully invoked I Neeeed Sticks! entry method.
1/19/2023 6:42:56 PM : Load order: 25, successfully invoked Where's Ma' Storage! entry method.
1/19/2023 6:42:56 PM : Load order: 26, successfully invoked Larger Scale entry method.

**Comment by Greenblyat** [comment]
Mod: Larger Scale
Version: 3.4.2
Location: Nexus

Loved this mod for a long time, but since updating Qmod Loader and all the other mods I have, only this one causes an infinite loading screen. Top of the order, bottom, middle, patch or no patch, its always only this mod causing the loading bar to stay at 100% and never finish. 

![image](https://user-images.githubusercontent.com/56848970/213593961-41e09fa2-6f57-4723-9aa2-a07b9e6f2444.png)

**Comment by Greenblyat** [comment]
Just now tried to go back to an old version, the problem is only with the most recent version. 3.4.1 is fine, 3.4.2 causes this bug.

**Comment by p1xel8ted** [comment]
Where is Player.log

**Comment by Greenblyat** [comment]
It wasn't my intention to just send that. Where the player log was described to be, it wasn't there and I haven't been able to find it.

**Comment by Greenblyat** [comment]
Wasn't my intention. Wasn't aware it would just send. Either way

Mono path[0] = 'D:/Steam/steamapps/common/Graveyard Keeper/Graveyard Keeper_Data/Managed'
Mono config path = 'D:/Steam/steamapps/common/Graveyard Keeper/MonoBleedingEdge/etc'
Initialize engine version: 2020.3.17f1 (a4537701e4ab)
[Subsystems] Discovering subsystems at path D:/Steam/steamapps/common/Graveyard Keeper/Graveyard Keeper_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 1060 3GB (ID=0x1c02)
    Vendor:   (null)
    VRAM:     2979 MB
    Driver:   31.0.15.2647
Begin MonoManager ReloadAssembly
- Completed reload, in  0.141 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.631700 ms
Odin Serializer ArchitectureInfo initialization with defaults (all unaligned read/writes disabled).

Odin Serializer detected whitelisted runtime platform WindowsPlayer and memory read test succeeded; enabling all unaligned memory read/writes.

Fallback handler could not load library D:/Steam/steamapps/common/Graveyard Keeper/Graveyard Keeper_Data/Mono/data-1698C690.dll
Fallback handler could not load library D:/Steam/steamapps/common/Graveyard Keeper/Graveyard Keeper_Data/Mono/data-1706C0E8.dll
[BeamMeUpGerry]: Parsed 'Z' for 'TeleportMenuKeyBind'.

[BeamMeUpGerry]: Parsed 'F5' for 'ReloadConfigKeyBind'.

[BeamMeUpGerry]: Parsed 'RB' for 'TeleportMenuControllerButton'.

[BringOutYerDead]: Parsed 'F5' for 'ReloadConfigKeyBind'.

[GerrysJunkTrunk]: Parsed 'F5' for 'ReloadConfigKeyBind'.

Fallback handler could not load library D:/Steam/steamapps/common/Graveyard Keeper/Graveyard Keeper_Data/Mono/data-1698BA88.dll
[PrayTheDayAway]: Parsed 'F5' for 'ReloadConfigKeyBind'.

[SaveNow]: Parsed 'K' for 'ManualSaveKeyBind'.

[SaveNow]: Parsed 'F5' for 'ReloadConfigKeyBind'.

[SaveNow]: Parsed 'LT' for 'ManualSaveControllerButton'.

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 0.198300 ms
****************************************
*** Starting Graveyard Keeper, ver. 1.405

Init: device name : NVIDIA GeForce GTX 1060 3GB, type: Desktop, model: Inspiron 5680 (Dell Inc.), ver: Direct3D 11.0 [level 11.1], screen: 1920x1080

Preloader.Awake, time = 0

Current system language: English

Stranger Sins DLC is available: False

D:/Steam/steamapps/common/Graveyard Keeper/Graveyard Keeper_Data

Game of Crone DLC is available: False

D:/Steam/steamapps/common/Graveyard Keeper/Graveyard Keeper_Data

Better Save Soul DLC is available: False

LoadGameSettings

Save default key bindings

Deserialize keyboard binding: 26

InitResolutions

Available: 640x480, scale = 2

Available: 720x480, scale = 2

Available: 720x576, scale = 2

Available: 800x600, scale = 2

Available: 1024x768, scale = 2

Available: 1152x864, scale = 2

Available: 1176x664, scale = 2

Available: 1280x720, scale = 2

Available: 1280x768, scale = 2

Available: 1280x800, scale = 2

Available: 1280x960, scale = 2

Available: 1280x1024, scale = 2

Available: 1360x768, scale = 2

Available: 1366x768, scale = 2

Available: 1400x1050, scale = 2

Available: 1440x900, scale = 2

Available: 1600x1200, scale = 2

Available: 1680x1050, scale = 2

Available: 1920x1080, scale = 2

NullReferenceException: Object reference not set to an instance of an object.
  at LargerScale.MainPatcher.ResolutionConfig_GetResolutionConfigOrNull (System.Int32 width, System.Int32 height, ResolutionConfig& __result) [0x00041] in <3b891ca6b58948c2aa33da2826763fe2>:0 
  at (wrapper dynamic-method) ResolutionConfig.ResolutionConfig.GetResolutionConfigOrNull_Patch1(int,int)
  at ResolutionConfig.InitResolutions () [0x00037] in <15f7d9bd98b742da8f4d3bc0d4bde4d2>:0 
  at Preloader.Awake () [0x00174] in <15f7d9bd98b742da8f4d3bc0d4bde4d2>:0 


Unloading 255 unused Assets to reduce memory usage. Loaded Objects now: 3494.
Total: 2.117600 ms (FindLiveObjects: 0.111100 ms CreateObjectMapping: 0.093200 ms MarkObjects: 1.752900 ms  DeleteObjects: 0.160200 ms)

Setting up 6 worker threads for Enlighten.
  Thread -> id: 12b8 -> priority: 1 
  Thread -> id: 1f08 -> priority: 1 
  Thread -> id: 4534 -> priority: 1 
  Thread -> id: e64 -> priority: 1 
  Thread -> id: 47cc -> priority: 1 
  Thread -> id: 2158 -> priority: 1

**Comment by p1xel8ted** [comment]
[LargerScale.zip](https://github.com/p1xel8ted/GYK-Mods-QMod/files/10465089/LargerScale.zip)

No idea why yours is failing. Try the attached one, working fine on my end.

**Comment by Greenblyat** [comment]
Still the same issue, but thank you for trying. If there's other information I could give, let me know. I'm not sure what could be the issue besides incompatibility, but that seems like a stretch.

**Comment by Greenblyat** [comment]
Do you mean me to send you all of my mods as they are?

**Comment by p1xel8ted** [comment]
Yep, so right click QMod directory - add to zip

**Comment by Greenblyat** [comment]
[QMods.zip](https://github.com/p1xel8ted/GYK-Mods-QMod/files/10471073/QMods.zip)

**Comment by p1xel8ted** [comment]
[LargerScale.v344.zip](https://github.com/p1xel8ted/GYK-Mods-QMod/files/10473307/LargerScale.v344.zip)

Should be fixed now.

**Comment by Greenblyat** [comment]
Oh hey! Thanks a bunch! Works great, appreciate it.
